name: publish_to_conda

on:
  release:
    types: [published]
  workflow_dispatch:   
    
jobs:
  publish:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: publish-to-conda
      uses: computed-axial-lithography/conda-package-publish-action@v1.6
      with:
        subDir: 'conda'
        platforms: 'win'
        AnacondaToken: ${{ secrets.ANACONDA_TOKEN }}


# on:
#   push:
#     branches: [main]
#   pull_reques:
#     branches: [main]

# jobs:
#   build:
#     runs-on:

#     steps:
#     - uses: actions/checkout@v2

#     - name: Setup miniconda
#       uses: 
